### ISSUE TITLE
Release source code

### ISSUE THREAD

**Issue by cesarmiquel** [Asia81/HackingToolkit9DS-Deprecated-#42]
Hi! It's unfortunate that you no longer have time or simply are tired of maintaining it. Have you considered releasing the source code? It might help debugging and maybe others can fix bugs, add features, etc.

**Comment by saphtea** [comment]
Please, this is an incredibly important tool to the 3DS community and while the source may not find immediate use, it will be much more likely that the 3DS will lead a longer lifespan either now or later if we have more important resources like this available.

Thank you so much for your work Asia81, I know we definitely must respect your decision if you want to keep it closed source, but it would be of great benefit to the 3DS community. Thank you again, hope you're doing well over there!
