### ISSUE TITLE
PKSM 7.0.1 Doesn't Work on my device

### ISSUE THREAD

**Issue by ArtilliRock** [Asia81/HackingToolkit9DS-Deprecated-#52]
Describe: When I load on, it says "Homebrew" Then it goes and i see the PKSM logo thing the it says 
                                                                         PKSM v7.0.1-3b12f3e0
Error during startup: 0xD900458B
Description: Archive :: init failed.

The worst thing is I don't know how to fix this...

**Comment by ArtilliRock** [comment]
Is there a newer one? If so, could you comment what the newer one's cia is. Thank you in advance.

**Comment by ArtilliRock** [comment]
> Describe: When I load on, it says "Homebrew" Then it goes and i see the PKSM logo thing the it says
> PKSM v7.0.1-3b12f3e0
> Error during startup: 0xD900458B
> Description: Archive :: init failed.
> The worst thing is I don't know how to fix this...
> I have my copy of pokemon ultra moob in too

**Comment by ArtilliRock** [comment]
moon sorry

**Comment by ArtilliRock** [comment]
Also I have my copy of Pokémon Ultra Moon in the 2ds

**Comment by Asia81** [comment]
Uh... Wrong Github, my friend.

**Comment by ArtilliRock** [comment]
Which is why there is PKSM post Sent from Mail for Windows 10 From: Asia81Sent: Wednesday, January 1, 2020 4:46 PMTo: Asia81/HackingToolkit9DS-Deprecated-Cc: ArtilliRock; AuthorSubject: Re: [Asia81/HackingToolkit9DS-Deprecated-] PKSM 7.0.1 Doesn't Work on my device (#52) Uh... Wrong Github, my friend.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
